config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
	
	resources :members
	
	resources :posts do
		resources :comments, only:[:create, :destroy]
	end
	
	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
	delete '/logout' => 'sessions#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :member
	belongs_to :post
	
	validates:comment, presence:true
end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :member
end

app/models/member.rb
class Member < ApplicationRecord
	has_one :detail
	has_many :posts
	has_many :comments
	
	has_secure_password
	before_save {self.email = email.downcase}
	VALID_EMAIL_REGEX=/\A[^@\s]+@[^@\s]+\z/
	
	validates:firstname, presence:true, length:{maximum:50}
	validates:lastname, presence:true, length:{maximum:50}
	validates:email, presence:true, length:{maximum:255},
					 format:{with:VALID_EMAIL_REGEX},
					 uniqueness:{case_sensitive:false}
	validates:password_digest, presence:true				
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :member
	has_many :comments
	
	validates:title, presence:true, length:{minimum:5}, uniqueness:true
	validates:body, presence:true, length:{maximum:255}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		if session[:user_id].nil?
			Comment.create(post_id:params[:post_id],
						   member_id:session[:user_id],
						   member_name:params[:writer],
						   comment:params[:comment])
			redirect_to post_path(params[:post_id])
		end
	end
	
	def destroy
		comment = Comment.find(params[:id])
		writer = comment.member_id
		if writer == session[:user_id]
			comment.destroy
		end
		redirect_to post_path(params[:post_id])
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def index
		@members = Member.all
	end
	
	def show
		@member = Member.find(params[:id])
		@detail = Detail.find_by(member_id:@member.id)
	end
	
	def create
		Member.create(firstname:params[:firstname],
					  lastname:params[:lastname],
					  email:params[:email].downcase,
					  password:params[:password],
					  password_confirmation:params[:confirm])
		member=Member.find_by(email:params[:email].downcase)
		if member.nil?
			render 'new'
		else
			Detail.create(member_id:member.id,
						  gender:params[:gender],
						  phone:params[:phone],
						  address:params[:address])
			redirect_to members_path
		end
	end
	
	def edit
		@member = Member.find(params[:id])
		@detail = Detail.find_by(member_id:params[:id])
	end
	
	def update
		member = Member.find(params[:id])
		member.firstname = params[:firstname]
		member.lastname = params[:lastname]
		member.email = params[:email]
		member.save
		
		detail = Detail.find_by(member_id:params[:id])
		detail.gender = params[:gender]
		detail.phone = params[:phone]
		detail.address = params[:address]
		detail.save
		
		redirect_to members_path
	end
	
	def destroy
		member = Member.find(params[:id])
		detail = Detail.find_by(member_id:member.id)
		detail.destroy
		member.destroy
		redirect_to members_path
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
	@posts = Post.all
  end
  
  def new
	if session[:user_id].nil?
		flash[:notice] = "Sign in to leave a post."
		redirect_to login_path
	end
  end
  
  def create
	id = session[:user_id]
	writer = Member.find(id)
	firstname = writer.firstname
	lastname = writer.lastname
	Post.create(member_id:id, 
				member_name:firstname+lastname, 
				title:params[:title], 
				body:params[:body])
	redirect_to :root
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		member = Member.find_by(email:params[:email].downcase)
		if member
			if member.authenticate(params[:password])
				session[:user_id] = member.id
				redirect_to :root
			else
				flash[:notice] = "Password is Wrong."
				redirect_to login_path
			end
		else
			flash[:notice] = "Such user does not exist."
			redirect_to login_path
		end
	end
	
	def delete
		session.delete(:user_id)
		redirect_to login_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Project8</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  	
		<script src='https://kit.fontawesome.com/a076d05399.js'></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		
		<style>
			label{
				color:rgb(0,100,200);
				font-size:15px;
				margin-top:8px;
			}
		</style>
	</head>

	<body>
  
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<%= link_to 'FirstBlog', root_path, class:"navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li class="active"><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Members', members_path %></li>
				<li><%= link_to 'Create Post', new_post_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% member = Member.find_by(id:session[:user_id]) %>
				<% if member.nil? %>
					<li><%= link_to 'SignUp', new_member_path, class:"glyphicon glyphicon-user" %></li>
					<li><%= link_to ' Login', login_path, class:"glyphicon glyphicon-log-in" %></li>
				<% else %>
					<li>
						<label style="background-color:white;color:black;padding:8px">
							User : <%=member.firstname%> <%=member.lastname%>
							<%= link_to 'MYPAGE', member_path(member.id) %>
						</label>
					</li>
					
					<li><%= link_to ' Logout', logout_path, method:"delete", class:"glyphicon glyphicon-log-out" %></li>
				<% end %>
			</ul>
		</div>
	</nav>
    
	<div class="container-fluid">
		<%= yield %>
	</div>
  </body>
</html>

app/views/members/edit.html.erb
<h1>Members#edit</h1>
<p>Find me in app/views/members/edit.html.erb</p>

<style>
	label{
		color:#f0ad4e;
		font-size:15px;
		margin-top:10px;
	}	
</style>

<style> 
input[type=text]:focus {
	box-shadow: 0px 0px 8px 0px #f0ad4e;
	border-color:#f0ad4e
}
input[type=email]:focus {
	box-shadow: 0px 0px 8px 0px #f0ad4e;
	border-color:#f0ad4e
}
input[type=password]:focus {
	box-shadow: 0px 0px 8px 0px #f0ad4e;
	border-color:#f0ad4e
}
input[type=submit]:focus {
	box-shadow: 0px 0px 8px 0px #f0ad4e;
	border-color:#f0ad4e
}
</style>

<div class="container">
	<h1>Edit Account</h1>
	<%=form_tag member_path(params[:id]), method:"patch" do%>
		<label>*Firstname :</label>
		<input type="text" name="firstname" class="form-control" value="<%=@member.firstname%>">
		
		<label>*Lastname :</label>
		<input type="text" name="lastname" class="form-control" value="<%=@member.lastname%>">
		
		<label>*E-Mail :</label>
		<input type="email" name="email" class="form-control" value="<%=@member.email%>">
		
		<label>Gender :</label>
		<input type="text" name="gender" class="form-control" value="<%=@detail.gender%>">
		
		<label>Phone number :</label>
		<input type="text" name="phone" class="form-control" value="<%=@detail.phone%>">
		
		<label>Address :</label>
		<input type="text" name="address" class="form-control" value="<%=@detail.address%>">
		
		<input type="submit" value="Edit Account" class="form-control btn btn-warning" style="margin-top:25px">
	<% end %>
</div>

app/views/members/index.html.erb
<h1>Members#index</h1>
<p>Find me in app/views/members/index.html.erb</p>

<div class="container-fluid">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Firstname</th>
				<th>Lastname</th>
				<th>Email</th>
				<th>More</th>
			</tr>
		</thead>
		<tbody>
			<% @members.each do |m| %>
				<tr>
					<td><%=m.firstname%></td>
					<td><%=m.lastname%></td>
					<td><%=m.email%></td>
					<td>
						<%= link_to 'Detail', member_path(m.id), class:"btn btn-success" %>
						<%= link_to 'Edit', edit_member_path(m.id), class:"btn btn-warning" %>
						<%= link_to 'Delete', member_path(m.id), data:{confirm:'Are you sure?'}, method:"delete", class:"btn btn-danger" %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/members/new.html.erb
<h1>Members#new</h1>
Find me in app/views/members/new.html.erb

<head>
	<style>
		label{
			color:rgb(0,100,200);
			font-size:15px;
			margin-top:10px;
		}
	</style>
</head>

<body>
<div class="container">
	<h1>Create Account</h1>
	<%=form_tag members_path do%>
		<label>*Firstname :</label>
		<input type="text" name="firstname" class="form-control">
		
		<label>*Lastname :</label>
		<input type="text" name="lastname" class="form-control">
		
		<label>*E-Mail :</label>
		<input type="email" name="email" class="form-control">
		
		<label>*Password :</label>
		<input type="password" name="password" class="form-control">
		
		<label>*Password_confirmation</label>
		<input type="password" name="confirm" class="form-control">
		
		<label>Gender :</label>
		<input type="text" name="gender" class="form-control">
		
		<label>Phone number :</label>
		<input type="text" name="phone" class="form-control">
		
		<label>Address :</label>
		<input type="text" name="address" class="form-control">
		
		<input type="submit" value="Create Account" class="form-control btn btn-primary" style="margin-top:25px">
	<% end %>
</div>
</body>

app/views/members/show.html.erb
<h1>Members#show</h1>
<p>Find me in app/views/members/show.html.erb</p>

<style>
	label{
		color:black;
	}
</style>

<div class="container">
	<h1>Member's Information</h1>
	<h1><% member = @member %></h1>
	<h1><% detail = @detail %></h1>
	
	<table class="table table-bordered" style="border-width:4px">
		<thead>
			<tr>
				<th></th>
				<th>Information</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><label style="color:#5cb85c">Membership</label></td>
				<td><label style="color:#5cb85c"><%=@member.id%></label></td>
			</tr>
			<tr>
				<td><label>Firstname</label></td>
				<td><%=member.firstname%></td>
			</tr>
			<tr>
				<td><label>Lastname</label></td>
				<td><%=member.lastname%></td>
			</tr>
			<tr>
				<td><label>E-Mail</label></td>
				<td><%=member.email%></td>
			</tr>
			
			<tr>
				<td><label>Gender</label></td>
				<td><%=detail.gender%></td>
			</tr>
			<tr>
				<td><label>Phone#</label></td>
				<td><%=detail.phone%></td>
			</tr>
			<tr>
				<td><label>E-Mail</label></td>
				<td><%=detail.address%></td>
			</tr>
			<tr>
				<%date = member.created_at %>
				<td><label style="color:#5cb85c">Created_at</label></td>
				<td><label style="color:#5cb85c"><%=date%></label></td>
			</tr>
			<tr>
				<%date = member.created_at %>
				<td><label style="color:#5cb85c">Updated_at</label></td>
				<td><label style="color:#5cb85c"><%=date%></label></td>
			</tr>
		</tbody>
	</table>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

<% @posts.each do |p| %>
	<div class="well">
		<h3><%= p.title %></h1>
		<p>
			<%=p.body%>
			
		</p>
		<p>
			<%= link_to 'Read More', post_path(p.id), class:"btn btn-default" %>
			<label style="float:right"><%=p.member_name%></label>
		</p>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_tag posts_path do %>
	<label>Title :</label>
	<input type="text" name="title" class="form-control">
	
	<label>Body :</label>
	<textarea name="body" class="form-control"></textarea>
	
	<input type="submit" value="Create Post" class="form-control btn btn-primary" style="margin-top:20px">
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<% post = Post.find(params[:id]) %>

<div class="container-fluid">
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	
	<hr>
	<%= link_to 'Edit', edit_post_path(post.id), class:"btn btn-default" %>
	<%= link_to 'Delete', post_path(post.id), class:"btn btn-danger" %>
	<hr>
	
	<div class="well">
		<% post.comments.each do |p| %>
			<label style="color:black"><%=p.member_name%></label>
			<%=p.comment%>
			<%=link_to '[X]', post_comment_path(:post_id=>post.id, :id=>p.id), method:"delete"%>
			<label style="float:right"><%=p.created_at%></label>
			<hr>
		<% end %>
		<%= form_tag post_comments_path(post.id) do%>
			<div class="input-group">
				<span class="input-group-addon">
					<i class="glyphicon glyphicon-user"></i>
				</span>
				<% if !session[:user_id].nil? %>
					<input type="text" name="writer" class="form-control" value="<%=Member.find(session[:user_id]).firstname%>" readonly style="background-color:white">
				<% else %>
					<input type="text" name="writer" class="form-control" value="Sign in to leave comment" readonly style="background-color:white">
				<% end %>
			</div>
			<div class="input-group">
				<span class="input-group-addon">
					<i class='fas fa-comment-alt'></i>
				</span>
				<input type="text" class="form-control" name="comment" placeholder="Comment">
				<span class="input-group-addon">
					<button type="submit" style="border:none; background:none;padding:0px">
						<i class="fa fa-send-o"></i>
					</button>
				</span>
			</div>
		<% end %>
	</div>
</div>